import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: [
    "dist/**",
    "build/**",
    "static/**",
    "public/**",
    "scratch/**",
    "src-tauri/**",
    "website/**",
    "venv/**",
    "graphify-out/**",
    ".agents/**",
    ".gemini/**",
    "tools/oxlint/anti-slop/**",
  ],
  plugins: ["react", "unicorn", "oxc"],
  categories: {
    correctness: "error",
  },
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
  ],
  rules: {
    "no-unused-vars": "error",
    "no-debugger": "error",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },
});
